import "./globals.css";
import "./fontawesome-all.min.css";
import "./main.css";
import type { Metadata } from "next";
import { preload } from "react-dom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
